### ISSUE TITLE
refactor: migrate to Material Design 3

### ISSUE THREAD

**Issue by WestFR** [Decathlon/vitamin-android#70]
This ticket is present as a reminder to ensure the migration to Material Design 3.

**Is your feature request related to a problem? Please describe.**

- Support last material version

**Describe the solution you'd like**

- Migrating from M2 to M3 (MDC 1.4.0 to MDC 1.5.0)

**Additional context**

- Documentation for migrating to Material Design 3 : https://material.io/blog/migrating-material-3

**Comment by GerardPaligot** [comment]
Thanks @WestFR for your issue!

At short term, we don't plan to support Material 3 because Vitamin shouldn't be specific to a platform (today, we have 3 implementation of the Design System with Web, iOS and Android). But we need to think how to map the semantic properties of Vitamin with semantic properties of Material You.

That was trivial with Material 2 but we need more reflexion about Material You support. We'll think about it in Q1 2022. Thanks for your issue, I keep it in our bugtracker. :)

**Comment by WestFR** [comment]
Thanks @GerardPaligot for you comment!

I'm totally agree with you (the semantic properties between MD2 and MD3 are some differents) on some components. So it's very trivial and tricky.

**Comment by lauthieb** [comment]
Hi everyone,
Thanks again for this proposition. Following our [important note](https://github.com/Decathlon/vitamin-design/blob/main/IMPORTANT_NOTE.md), we will not be able to do this in this implementation but we will think about this for our next version (inner sourced for the moment).
Thanks for your understanding and your proposition @WestFR.
